export const SAP_INFRA_TERMS = Object.freeze({
  landscapeHealth: 'SAP Performance Status',
  applicationServers: 'Application Servers',
  resourceTrend: 'Server Performance Trend',
  historicalRca: 'RCA Detail',
  sapWorkload: 'SAP Job',
  historicalWorkload: 'SAP Job History',
  criticalWorkProcess: 'Critical WP',
  backgroundJob: 'Background Job',
  abapProgram: 'ABAP Program',
  workProcess: 'Work Process',
  sapUser: 'SAP User',
  osPid: 'PID',
  collectionCycle: 'Rundeck Run',
  telemetryCoverage: 'Servers',
  collector: 'Rundeck',
  database: 'PostgreSQL',
  lastCollection: 'Last Check',
})
