export const SAP_INFRA_TERMS = Object.freeze({
  landscapeHealth: 'SAP Landscape Health',
  applicationServers: 'Application Servers',
  resourceTrend: 'Application Server Resource Trend',
  historicalRca: 'Historical RCA',
  sapWorkload: 'SAP Workload',
  historicalWorkload: 'Historical SAP Workload',
  criticalWorkProcess: 'Critical Work Process',
  backgroundJob: 'Background Job',
  abapProgram: 'ABAP Program',
  workProcess: 'Work Process',
  sapUser: 'SAP User',
  osPid: 'OS PID',
  collectionCycle: 'Collection Cycle',
  telemetryCoverage: 'Telemetry Coverage',
  collector: 'Rundeck Collector',
  database: 'PostgreSQL',
  lastCollection: 'Last Collection',
})
