#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${APP_DIR:-/root/rundeck-sphere-dev}"
POSTGRES_ENV="${POSTGRES_ENV:-/etc/sphere/rundeck-db.env}"
VENV_DIR="${VENV_DIR:-${APP_DIR}/.venv-db}"

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-sap_rca_dev}"
DB_USER="${DB_USER:-sap_rca_app}"
DB_MODE="${DB_MODE:-hybrid}"

STATUS_DIR="${APP_DIR}/runtime-status"
STATUS_FILE="${STATUS_DIR}/sap-db-layer-smoke-status.md"

log() {
  printf '\n[sap-db-layer-smoke] %s\n' "$*"
}

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

[ -d "$APP_DIR" ] || fail "APP_DIR not found: ${APP_DIR}"
[ -f "$POSTGRES_ENV" ] || fail "Credential file not found: ${POSTGRES_ENV}"

cd "$APP_DIR"

set -a
# shellcheck disable=SC1090
source "$POSTGRES_ENV"
set +a

: "${SAP_RCA_APP_PASSWORD:?SAP_RCA_APP_PASSWORD missing in ${POSTGRES_ENV}}"

log "Preparing project-local Python virtualenv"
python3 -m venv "$VENV_DIR"
# shellcheck disable=SC1091
source "${VENV_DIR}/bin/activate"

python -m pip install --upgrade pip >/dev/null
python -m pip install -r backend/requirements.txt >/dev/null

export DB_MODE
export DATABASE_URL="postgresql+psycopg://${DB_USER}:${SAP_RCA_APP_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

log "Running DB layer smoke test"
mkdir -p "$STATUS_DIR"

python - <<'PY' | tee "$STATUS_FILE"
from __future__ import annotations

import json
from datetime import datetime, timezone

from backend.db.session import check_database
from backend.db.repositories import (
    upsert_case_best_effort,
    upsert_evidence_best_effort,
    insert_parsed_result_best_effort,
)

now = datetime.now(timezone.utc).isoformat()
case_id = "CASE-SMOKE-DB-LAYER"

case_data = {
    "id": case_id,
    "case_no": case_id,
    "title": "DB Layer Smoke Test",
    "sid": "TST",
    "environment": "DEV",
    "severity": "INFO",
    "status": "OPEN",
    "summary": "Smoke test generated by scripts/test-sap-db-layer.sh",
    "top_anomaly": "",
    "top_suspect": "",
    "created_by": "sap-db-smoke",
    "created_at": now,
    "updated_at": now,
}

evidence_data = {
    "id": "evidence-smoke-db-layer",
    "case_id": case_id,
    "tool": "smoke-test",
    "sid": "TST",
    "title": "Smoke Evidence",
    "original_filename": "smoke.log",
    "stored_filename": "smoke.log",
    "stored_path": "evidence/smoke.log",
    "checksum_sha256": "",
    "size_bytes": 0,
    "mime_type": "text/plain",
    "ext": ".log",
    "note": "Smoke evidence metadata only",
    "tags": ["smoke", "db-layer"],
    "created_at": now,
    "updated_at": now,
}

parsed_result = {
    "id": "parsed-smoke-db-layer",
    "evidence_id": "evidence-smoke-db-layer",
    "tool": "smoke-test",
    "parser_version": "smoke-v1",
    "verdict": "OK",
    "severity": "INFO",
    "confidence": 1.0,
    "top_anomaly": "",
    "top_suspect": "",
    "summary": "DB layer smoke parsed result",
    "result_json": {"smoke": True},
    "created_at": now,
}

status = {
    "checked_at": now,
    "database": check_database(),
    "case_write": upsert_case_best_effort(case_data),
    "evidence_write": upsert_evidence_best_effort(evidence_data),
    "parsed_result_write": insert_parsed_result_best_effort(case_id, parsed_result),
}

print("# SAP RCA DB Layer Smoke Status")
print()
print("```json")
print(json.dumps(status, indent=2, sort_keys=True))
print("```")
PY

log "Smoke status written to ${STATUS_FILE}"
