import React from 'react'
import { ResponsiveContainer, LineChart, Line, CartesianGrid, XAxis, YAxis, Tooltip, Legend, ReferenceArea } from 'recharts'
import CaseLinkPanel from '../features/cases/CaseLinkPanel.jsx'
import useCaseHistoryLink from '../features/cases/useCaseHistoryLink.js'
import { expandZipAwareFiles, fileExt, loadJson, saveJson } from './evidence-utils.js'
import { buildLogAnalysis, parseLogText, sortJobs } from './logAnalysis2026.js'
import './RcaWorkspace2026.css'

const CASE_KEY = 'sap_rca_log_v11_case'
const JOB_SORTS = [['rss', 'By RAM (RSS)'], ['cpu', 'By CPU'], ['persistence', 'By persistence'], ['errors', 'By errors']]

function formatNumber(value, digits = 0) { return Number(value || 0).toLocaleString('en-US', { maximumFractionDigits: digits }) }
function snapshotDate(value = '') { return String(value || '').match(/\d{4}-\d{2}-\d{2}/)?.[0] || '—' }
function buildCasePayload(analysis, title) { const top = analysis?.jobs?.[0]; return { title, severity: analysis?.incidentSnapshots?.length ? 'CRIT' : 'INFO', summary: analysis ? `LOG window ${analysis.analysisWindow.start}-${analysis.analysisWindow.end}; incident ${analysis.incidentWindow.start}-${analysis.incidentWindow.end}.` : '', top_anomaly: top?.name || analysis?.primaryHost || '', top_suspect: top?.program || top?.name || '', status: 'OPEN', created_by: 'sap-rca-workspace-v1.1' } }
function buildParsedPayload(analysis) { return { tool: 'LOG Analysis v1.1', verdict: analysis?.incidentSnapshots?.length ? 'Incident window detected' : 'No critical window detected', severity: analysis?.incidentSnapshots?.length ? 'CRIT' : 'INFO', confidence: 0, top_anomaly: analysis?.jobs?.[0]?.name || analysis?.primaryHost || '', top_suspect: analysis?.jobs?.[0]?.program || '', summary: analysis ? `Analysis window ${analysis.analysisWindow.start}-${analysis.analysisWindow.end}; ${analysis.primarySnapshots.length} primary-host snapshot(s).` : '', result_json: { primaryHost: analysis?.primaryHost || '', analysisWindow: analysis?.analysisWindow || null, incidentWindow: analysis?.incidentWindow || null, peaks: analysis?.peaks || null, hostComparison: analysis?.hostComparison || [], jobs: (analysis?.jobs || []).slice(0, 50), errors: analysis?.errors || [], primarySnapshots: analysis?.primarySnapshots || [] } } }

function ResourceTooltip({ active, payload, label }) {
  if (!active || !payload?.length) return null
  const row = payload[0]?.payload || {}
  return <div className="rca26Tooltip"><strong>{label}</strong><span>CPU {formatNumber(row.cpuPct, 1)}%</span><span>RAM {formatNumber(row.memoryPct, 1)}%</span><span>Load/vCPU {formatNumber(row.loadRatio, 2)}</span><span>Swap In {formatNumber(row.swapIn)} p/s</span><span>WP Critical {formatNumber(row.wpCritical)}</span></div>
}
function Metric({ label, value, meta, tone = '' }) { return <div className={`rca26Metric ${tone}`}><span>{label}</span><strong>{value}</strong>{meta ? <small>{meta}</small> : null}</div> }
function JobDetail({ job }) {
  if (!job) return <div className="rca26Empty compact">Select a job/process row to inspect SAP and OS identifiers.</div>
  const rss = job.peakRssRecord || {}; const cpu = job.peakCpuRecord || {}
  return <div className="rca26Detail"><div className="rca26DetailTitle"><span>Selected job / process</span><strong title={job.name}>{job.name}</strong></div><dl><div><dt>Program</dt><dd>{job.program || '—'}</dd></div><div><dt>Host</dt><dd>{job.host}</dd></div><div><dt>Instance</dt><dd>{rss.instance || cpu.instance || '—'}</dd></div><div><dt>WP / Type</dt><dd>{job.topWp || '—'} / {job.topType || '—'}</dd></div><div><dt>PID</dt><dd>{job.topPid || '—'}</dd></div><div><dt>State</dt><dd>{job.topState || '—'}</dd></div><div><dt>Peak CPU</dt><dd>{formatNumber(job.peakCpu, 1)}% @ {cpu.timeLabel || '—'}</dd></div><div><dt>Peak RSS</dt><dd>{formatNumber(job.peakRss, 2)} GB @ {rss.timeLabel || '—'}</dd></div><div><dt>First / Last seen</dt><dd>{job.firstSeen} / {job.lastSeen}</dd></div><div><dt>Snapshots seen</dt><dd>{job.persistenceText}</dd></div><div><dt>Errors</dt><dd>{job.errors.length ? job.errors.join(', ') : '—'}</dd></div></dl><div className="rca26SapLookup"><b>SAP lookup</b><span>SM37 by Job Name · SM50/SM66 by WP, PID, program and instance.</span></div></div>
}

export default function ToolLogAnalysis2026({ processMode = false }) {
  const [files, setFiles] = React.useState([]); const [busy, setBusy] = React.useState(false); const [status, setStatus] = React.useState('Upload multiple OS/WP-SCOUT log snapshots to build the timeline.'); const [analysis, setAnalysis] = React.useState(null); const [jobSort, setJobSort] = React.useState('rss'); const [selectedJobKey, setSelectedJobKey] = React.useState('')
  const caseLink = useCaseHistoryLink({ storageKey: CASE_KEY, buildCasePayload, buildParsedPayload, defaultCaseTitle: 'LOG RCA Case', toolName: 'LOG Analysis v1.1', uploadTags: ['log', 'wp-scout', 'rca-v1.1'], requireExplicitSaveIntent: true, loadJson, saveJson })
  const analyzeFiles = React.useCallback(async (nextFiles) => { setBusy(true); setStatus('Parsing snapshots, host telemetry, jobs, work processes and errors…'); try { const parsed = []; for (const file of nextFiles) parsed.push(parseLogText(await file.text(), file.name)); const result = buildLogAnalysis(parsed); setAnalysis(result); setStatus(`Parsed ${result.primarySnapshots.length} primary-host snapshot(s) across ${new Set(result.telemetry.map((row) => row.host)).size} host(s).`) } catch (error) { setStatus(error?.message || 'Failed to analyze LOG evidence.') } finally { setBusy(false) } }, [])
  const onFiles = React.useCallback(async (fileList) => { setBusy(true); try { const expanded = (await expandZipAwareFiles(fileList, ['log', 'txt', 'csv'])).filter((file) => ['log', 'txt', 'csv'].includes(fileExt(file.name))); setFiles(expanded); await analyzeFiles(expanded) } catch (error) { setStatus(error?.message || 'Failed to read uploaded logs.'); setBusy(false) } }, [analyzeFiles])
  const baseJobs = processMode ? (analysis?.jobsAll || []) : (analysis?.jobs || []); const sortedJobs = React.useMemo(() => sortJobs(baseJobs, jobSort), [baseJobs, jobSort]); const selectedJob = sortedJobs.find((item) => item.key === selectedJobKey) || sortedJobs[0] || null
  React.useEffect(() => { if (sortedJobs.length && !sortedJobs.some((item) => item.key === selectedJobKey)) setSelectedJobKey(sortedJobs[0].key) }, [sortedJobs, selectedJobKey])
  const snapshots = analysis?.primarySnapshots || []; const peaks = analysis?.peaks || {}; const incident = analysis?.incidentWindow || { start: '—', end: '—', count: 0 }; const peakSnapshot = analysis?.peakSnapshot || null; const analysisWindow = analysis?.analysisWindow || { start: '—', end: '—', count: 0 }; const severity = analysis?.incidentSnapshots?.length ? 'CRIT' : analysis ? 'NORMAL' : 'WAITING'; const date = snapshotDate(peakSnapshot?.snapshot || snapshots[0]?.snapshot); const selectedHistory = [...(selectedJob?.records || [])].sort((a, b) => a.sortKey - b.sortKey)
  return <section className="rca26Shell"><div className="rca26Inner">
    <header className="rca26Head"><div><h1>{processMode ? 'LOG Processes & Jobs' : 'LOG Analysis'}</h1><p>Time-window troubleshooting from OS resource snapshots to SAP job, program, WP and PID.</p></div><label className="rca26Upload"><input type="file" multiple accept=".zip,.log,.txt,.csv" onChange={(event) => onFiles(event.target.files)} />{busy ? 'Parsing…' : 'Upload Logs'}</label></header>
    <nav className="rca26Tabs compact"><a href="#/log" data-active={processMode ? 'false' : 'true'}>Overview</a><a href="#/tool/logs/process" data-active={processMode ? 'true' : 'false'}>Jobs & Processes</a><a href="#log-errors">Errors</a><a href="#log-evidence">Evidence</a></nav>
    <section className="rca26MetricStrip"><Metric label="Analysis window" value={`${analysisWindow.start} – ${analysisWindow.end}`} meta={`${date} · ${analysisWindow.count} snapshot(s)`} /><Metric label="System / Host" value={analysis?.primaryHost || '—'} meta={peakSnapshot ? `SID ${peakSnapshot.sid || '—'} · Inst ${peakSnapshot.instance || '—'} · vCPU ${peakSnapshot.vcpu || '—'}` : status} /><Metric label="Incident" value={severity} meta={incident.count ? `${incident.start} – ${incident.end}` : 'No critical window'} tone={severity === 'CRIT' ? 'critical' : 'good'} /><Metric label="Peak CPU" value={`${formatNumber(peaks.cpu?.value, 1)}%`} meta={peaks.cpu?.time ? `at ${peaks.cpu.time}` : '—'} /><Metric label="Peak RAM" value={`${formatNumber(peaks.ram?.value, 1)}%`} meta={peaks.ram?.time ? `at ${peaks.ram.time}` : '—'} tone={Number(peaks.ram?.value || 0) >= 85 ? 'critical' : ''} /><Metric label="Peak Load / vCPU" value={formatNumber(peaks.load?.value, 2)} meta={peaks.load?.time ? `at ${peaks.load.time}` : '—'} tone={Number(peaks.load?.value || 0) >= 1.5 ? 'critical' : ''} /><Metric label="Peak Swap In" value={formatNumber(peaks.swapIn?.value)} meta={peaks.swapIn?.time ? `p/s at ${peaks.swapIn.time}` : '—'} tone={Number(peaks.swapIn?.value || 0) >= 1000 ? 'warn' : ''} /><Metric label="WP Critical (peak)" value={formatNumber(peaks.wpCritical?.value)} meta={peaks.wpCritical?.time ? `at ${peaks.wpCritical.time}` : '—'} /></section>
    <div className="rca26Grid logMain"><section className="rca26Panel"><div className="rca26PanelHead"><div><h2>Resource Timeline</h2><p>Real snapshot points only. Peaks are calculated independently for CPU, RAM, load/vCPU and swap-in.</p></div><span className="rca26Tag">10-min snapshots</span></div>{snapshots.length ? <div className="rca26Chart tall wideChart"><ResponsiveContainer width="100%" height="100%"><LineChart data={snapshots} margin={{ top: 10, right: 48, left: 0, bottom: 8 }}><CartesianGrid strokeDasharray="3 6" vertical={false}/><XAxis dataKey="timeLabel"/><YAxis yAxisId="pct" domain={[0,100]} tickFormatter={(v)=>`${v}%`}/><YAxis yAxisId="load" orientation="right" domain={[0,'auto']} width={36}/><YAxis yAxisId="swap" orientation="right" domain={[0,'auto']} width={48} hide/>{incident.count ? <ReferenceArea yAxisId="pct" x1={incident.start} x2={incident.end} fill="#10b9a8" fillOpacity={0.08} stroke="#20d8c8" strokeDasharray="4 4"/> : null}<Tooltip content={<ResourceTooltip/>}/><Legend/><Line yAxisId="pct" type="linear" dataKey="cpuPct" name="CPU %" stroke="#35d4cf" strokeWidth={2.2} dot={{r:4}} connectNulls={false}/><Line yAxisId="pct" type="linear" dataKey="memoryPct" name="RAM %" stroke="#4d8fff" strokeWidth={2.2} dot={{r:4}} connectNulls={false}/><Line yAxisId="load" type="linear" dataKey="loadRatio" name="Load / vCPU" stroke="#ff6b57" strokeWidth={2} dot={{r:4}} connectNulls={false}/><Line yAxisId="swap" type="linear" dataKey="swapIn" name="Swap In (p/s)" stroke="#f5a623" strokeWidth={2} dot={{r:4}} connectNulls={false}/></LineChart></ResponsiveContainer></div> : <div className="rca26Empty">{status}</div>}{snapshots.length ? <div className="rca26StatusLine">{snapshots.map((row)=><span key={`${row.snapshot}-${row.host}`} className={row.severity.toLowerCase()}><b>{row.timeLabel}</b>{row.severity}</span>)}</div> : null}</section>
      <aside className="rca26Stack"><section className="rca26Panel compactPanel"><div className="rca26PanelHead"><div><h2>Resource Peaks</h2><p>Peak time can differ per metric.</p></div></div><div className="rca26KeyValue"><span>CPU</span><b>{formatNumber(peaks.cpu?.value,1)}%</b><small>{peaks.cpu?.time||'—'}</small></div><div className="rca26KeyValue"><span>RAM</span><b>{formatNumber(peaks.ram?.value,1)}%</b><small>{peaks.ram?.time||'—'}</small></div><div className="rca26KeyValue"><span>Load/vCPU</span><b>{formatNumber(peaks.load?.value,2)}</b><small>{peaks.load?.time||'—'}</small></div><div className="rca26KeyValue"><span>Swap In</span><b>{formatNumber(peaks.swapIn?.value)} p/s</b><small>{peaks.swapIn?.time||'—'}</small></div><div className="rca26KeyValue"><span>WP Critical</span><b>{formatNumber(peaks.wpCritical?.value)}</b><small>{peaks.wpCritical?.time||'—'}</small></div></section><section className="rca26Panel compactPanel"><div className="rca26PanelHead"><div><h2>At Peak ({analysis?.peakTime || '—'})</h2><p>Primary-host OS and SAP snapshot.</p></div></div>{peakSnapshot ? <div className="rca26Snapshot"><div><span>Host</span><b>{peakSnapshot.host}</b></div><div><span>CPU</span><b>{formatNumber(peakSnapshot.cpuPct,1)}%</b></div><div><span>RAM</span><b>{formatNumber(peakSnapshot.memoryPct,1)}%</b></div><div><span>Load 1/5/15</span><b>{formatNumber(peakSnapshot.load1,2)} / {formatNumber(peakSnapshot.load5,2)} / {formatNumber(peakSnapshot.load15,2)}</b></div><div><span>Load/vCPU</span><b>{formatNumber(peakSnapshot.loadRatio,2)}</b></div><div><span>Swap In/Out</span><b>{formatNumber(peakSnapshot.swapIn)} / {formatNumber(peakSnapshot.swapOut)} p/s</b></div><div><span>WP Run/Standby/Crit</span><b>{peakSnapshot.wpRunning} / {peakSnapshot.wpStandby} / {peakSnapshot.wpCritical}</b></div><div><span>Dialog/BTC/UPD</span><b>{peakSnapshot.wpDialog} / {peakSnapshot.wpBtc} / {peakSnapshot.wpUpd}</b></div></div> : <div className="rca26Empty compact">No snapshot.</div>}</section></aside>
    </div>
    <div className="rca26Grid two"><section className="rca26Panel"><div className="rca26PanelHead"><div><h2>Host Comparison at Peak</h2><p>Confirms whether pressure is host-specific or system-wide.</p></div></div><div className="rca26TableWrap short"><table className="rca26Table"><thead><tr><th>Host</th><th>CPU</th><th>RAM</th><th>Load/vCPU</th><th>Swap In</th><th>WP Crit</th></tr></thead><tbody>{(analysis?.hostComparison||[]).map((row)=><tr key={`${row.host}-${row.timeLabel}`}><td>{row.host}</td><td>{formatNumber(row.cpuPct,1)}%</td><td>{formatNumber(row.memoryPct,1)}%</td><td>{formatNumber(row.loadRatio,2)}</td><td>{formatNumber(row.swapIn)}</td><td>{row.wpCritical}</td></tr>)}</tbody></table></div></section><section className="rca26Panel" id="log-evidence"><div className="rca26PanelHead"><div><h2>Raw Snapshot List</h2><p>Primary host values exactly as collected; no interpolated timestamps.</p></div></div><div className="rca26TableWrap short"><table className="rca26Table"><thead><tr><th>Time</th><th>CPU</th><th>RAM</th><th>Load/vCPU</th><th>Swap In</th><th>WP Crit</th><th>Status</th></tr></thead><tbody>{snapshots.map((row)=><tr key={`${row.snapshot}-${row.host}`}><td>{row.timeLabel}</td><td>{formatNumber(row.cpuPct,2)}%</td><td>{formatNumber(row.memoryPct,1)}%</td><td>{formatNumber(row.loadRatio,2)}</td><td>{formatNumber(row.swapIn)}</td><td>{row.wpCritical}</td><td><span className={`rca26Status ${row.severity.toLowerCase()}`}>{row.severity}</span></td></tr>)}</tbody></table></div></section></div>
    <section className="rca26Panel" id="log-jobs"><div className="rca26PanelHead jobHead"><div><h2>{processMode ? 'Jobs / Programs in Analysis Window' : `Jobs / Programs During Incident (${incident.start} – ${incident.end})`}</h2><p>Job is the primary troubleshooting object; WP and PID are retained for SAP cross-check.</p></div><div className="rca26ToggleGroup">{JOB_SORTS.map(([id,label])=><button type="button" key={id} data-active={jobSort===id} onClick={()=>setJobSort(id)}>{label}</button>)}</div></div><div className="rca26TableWrap jobs"><table className="rca26Table selectable"><thead><tr><th>Job / Process</th><th>Program</th><th>Type</th><th>WP</th><th>PID</th><th>State</th><th>Avg CPU</th><th>Peak CPU</th><th>Peak RSS</th><th>Seen</th><th>Errors</th></tr></thead><tbody>{sortedJobs.slice(0,50).map((item)=><tr key={item.key} data-selected={item.key===selectedJob?.key} onClick={()=>setSelectedJobKey(item.key)}><td title={item.name}>{item.name}</td><td title={item.program}>{item.program}</td><td>{item.topType}</td><td>{item.topWp}</td><td>{item.topPid}</td><td>{item.topState}</td><td>{formatNumber(item.avgCpu,1)}%</td><td>{formatNumber(item.peakCpu,1)}%</td><td>{formatNumber(item.peakRss,2)} GB</td><td>{item.persistenceText}</td><td>{item.errors.length ? item.errors.join(', ') : '—'}</td></tr>)}</tbody></table></div></section>
    <div className="rca26Grid logDetail"><section className="rca26Panel"><JobDetail job={selectedJob}/></section><section className="rca26Panel"><div className="rca26PanelHead"><div><h2>Job Resource History</h2><p>Same job/program across actual uploaded snapshots.</p></div></div><div className="rca26TableWrap"><table className="rca26Table"><thead><tr><th>Time</th><th>PID</th><th>WP</th><th>Type</th><th>State</th><th>CPU</th><th>RSS</th><th>RABAX</th><th>Error</th></tr></thead><tbody>{selectedHistory.map((row)=><tr key={`${row.snapshot}-${row.pid}-${row.wp}`}><td>{row.timeLabel}</td><td>{row.pid}</td><td>{row.wp}</td><td>{row.type}</td><td>{row.state}</td><td>{formatNumber(row.cpu,1)}%</td><td>{formatNumber(row.rssGb,2)} GB</td><td>{formatNumber(row.rabax)}</td><td>{row.errorCode !== '?' ? row.errorCode : '—'}</td></tr>)}</tbody></table></div></section></div>
    <section className="rca26Panel" id="log-errors"><div className="rca26PanelHead"><div><h2>Error Evidence During Incident</h2><p>Secondary evidence only. Counts are deduplicated by snapshot and unique WP/PID, not raw repeated section rows.</p></div></div><div className="rca26TableWrap short"><table className="rca26Table"><thead><tr><th>Error Code</th><th>Snapshot records</th><th>Unique WP/PID</th><th>Affected jobs</th><th>First seen</th><th>Last seen</th></tr></thead><tbody>{(analysis?.errors||[]).map((item)=><tr key={item.errorCode}><td>{item.errorCode}</td><td>{item.snapshotRecords}</td><td>{item.uniqueProcesses}</td><td>{item.affectedJobs}</td><td>{item.firstSeen}</td><td>{item.lastSeen}</td></tr>)}</tbody></table></div></section>
    <section className="rca26Case"><div><span>Evidence</span><strong>{files.length} uploaded file(s)</strong><small>{status}</small></div><div className="rca26CaseActions"><a className="rca26Link" href="#/cases">History</a><button className="rca26Btn" type="button" onClick={()=>document.getElementById('log-case-v11')?.toggleAttribute('open')}>Case</button></div></section><details className="rca26Disclosure" id="log-case-v11"><summary>Case persistence</summary><div className="rca26DisclosureBody"><CaseLinkPanel title="LOG case" description="Create or link a case only after reviewing the resource timeline and job/PID evidence." caseId={caseLink.caseId} caseTitle={caseLink.caseTitle} recentCases={caseLink.recentCases} savingCase={caseLink.savingCase} creatingCase={caseLink.creatingCase} saveStatus={caseLink.saveStatus} onCaseIdChange={caseLink.setCaseId} onCaseTitleChange={caseLink.setCaseTitle} onCreateCase={()=>caseLink.createLinkedCase(analysis)} onSaveCurrent={(options)=>caseLink.persistAnalysis(analysis, files, {}, options)} hasAnalysis={Boolean(analysis)} saveLabel="Save LOG analysis" titlePlaceholder="Example: AOP PRD slow 15:20"/></div></details>
  </div></section>
}
