import React from 'react'
import {ResponsiveContainer,LineChart,Line,BarChart,Bar,CartesianGrid,XAxis,YAxis,Tooltip,Legend,Brush} from 'recharts'
import CaseLinkPanel from '../features/cases/CaseLinkPanel.jsx'
import useCaseHistoryLink from '../features/cases/useCaseHistoryLink.js'
import {expandSt03nFiles,REQUIRED_ST03N} from './parsers/st03nParser.js'
import {loadJson,saveJson} from './evidence-utils.js'
import {analyzeSt03nFiles,transactionDecomposition} from './st03nAnalysis2026.js'
import './RcaWorkspace2026.css'

const CASE_KEY='sap_rca_st03n_v121_case'
const n=(v,d=0)=>Number(v||0).toLocaleString('en-US',{maximumFractionDigits:d}),sh=(v='',m=28)=>String(v).length>m?`${String(v).slice(0,m-1)}…`:String(v)
const Metric=({label,value,meta,tone=''})=><div className={`rca26Metric ${tone}`}><span>{label}</span><strong title={String(value)}>{value}</strong><small>{meta||'—'}</small></div>
const numH=x=>({label:x,num:true})
function Table({heads,rows,className=''}){return <div className={`rca26TableWrap ${className}`}><table className="rca26Table"><thead><tr>{heads.map((h,i)=><th key={i} className={h.num?'num':''}>{h.label||h}</th>)}</tr></thead><tbody>{rows}</tbody></table></div>}
function Tip({active,payload,label}){if(!active||!payload?.length)return null;const r=payload[0].payload;return <div className="rca26Tooltip"><strong>{label}</strong><span>Avg Response {n(r.avgResponseMs,1)} ms</span><span>DB {n(r.avgDbMs,1)} ms</span><span>CPU {n(r.avgCpuMs,1)} ms</span><span>Wait + Roll {n(r.avgWaitTotalMs,1)} ms</span><span>Steps {n(r.steps)}</span></div>}
function workerParse(files){return new Promise((resolve,reject)=>{if(typeof Worker==='undefined')return reject(new Error('Worker unavailable'));const w=new Worker(new URL('./workers/st03nParser.worker.js',import.meta.url),{type:'module'});w.onmessage=e=>{w.terminate();e.data?.ok?resolve(e.data.analysis):reject(new Error(e.data?.error||'Worker failed'))};w.onerror=e=>{w.terminate();reject(new Error(e.message||'Worker failed'))};w.postMessage({files})})}
function buildCasePayload(a,title){return{title,severity:'INFO',summary:a?`ST03N ${a.coverage.filter(x=>x.ok).length}/${REQUIRED_ST03N.length} groups parsed; ${a.consistencyCheckCount||0} consistency check(s).`:'',top_anomaly:a?.topTransaction?.object||a?.topResponseRecord?.label||'',top_suspect:a?.topResponseRecord?.program||'',status:'OPEN',created_by:'sap-rca-workspace-v1.2.1'}}
function buildParsedPayload(a){return{tool:'ST03N Analysis v1.2.1',verdict:'ST03N workload parsed',severity:'INFO',confidence:0,top_anomaly:a?.topTransaction?.object||'',top_suspect:a?.topResponseRecord?.program||'',summary:a?`${a.totalRows} normalized ST03N rows; ${a.consistencyCheckCount||0} source consistency check(s).`:'',result_json:{coverage:a?.coverage,consistencyCheckCount:a?.consistencyCheckCount,peakInterval:a?.peakInterval,topTransaction:a?.topTransaction,topResponseRecord:a?.topResponseRecord,topDbRecord:a?.topDbRecord,timeProfile:a?.timeProfile,taskTypes:a?.taskTypes,transactions:(a?.transactions||[]).slice(0,100),responseRecords:(a?.responseRecords||[]).slice(0,100),dbRecords:(a?.dbRecords||[]).slice(0,100)}}}

export default function ToolSt03nAnalysis2026(){
 const [files,setFiles]=React.useState([]),[busy,setBusy]=React.useState(false),[status,setStatus]=React.useState('Upload the five ST03N exports or a ZIP pack.'),[a,setA]=React.useState(null),[allTx,setAllTx]=React.useState(false),[allResp,setAllResp]=React.useState(false),[allDb,setAllDb]=React.useState(false)
 const caseLink=useCaseHistoryLink({storageKey:CASE_KEY,buildCasePayload,buildParsedPayload,defaultCaseTitle:'ST03N RCA Case',toolName:'ST03N Analysis v1.2.1',uploadTags:['st03n','rca-v1.2.1'],loadJson,saveJson})
 const analyze=React.useCallback(async fs=>{setBusy(true);setStatus('Parsing ST03N exports…');try{let result;try{result=await workerParse(fs)}catch{result=await analyzeSt03nFiles(fs)}setA(result);setAllTx(false);setAllResp(false);setAllDb(false);setStatus(`Parsed ${result.totalRows} rows from ${result.coverage.filter(x=>x.ok).length}/${REQUIRED_ST03N.length} evidence groups.`)}catch(e){setStatus(e?.message||'ST03N parse failed.')}finally{setBusy(false)}},[])
 const upload=React.useCallback(async list=>{setBusy(true);try{const fs=await expandSt03nFiles(list);setFiles(fs);await analyze(fs)}catch(e){setStatus(e?.message||'Upload failed.');setBusy(false)}},[analyze])
 const workload=a?.workloadTransactions||a?.transactions||[],dec=React.useMemo(()=>transactionDecomposition(workload,8),[workload]),ok=a?.coverage?.filter(x=>x.ok).length||0,peak=a?.peakInterval?.row,tx=a?.topTransaction,resp=a?.topResponseRecord,db=a?.topDbRecord,max=Math.max(1,...workload.slice(0,8).map(x=>Number(x.totalResponseSec||0))),packDate=resp?.timestamp?.slice(0,10)||db?.timestamp?.slice(0,10)||'—'
 const txRows=allTx?(a?.transactions||[]):(a?.transactions||[]).slice(0,15),respRows=allResp?(a?.responseRecords||[]):(a?.responseRecords||[]).slice(0,15),dbRows=allDb?(a?.dbRecords||[]):(a?.dbRecords||[]).slice(0,15)
 return <section className="rca26Shell"><div className="rca26Inner">
  <header className="rca26Head"><div><h1>ST03N Analysis</h1><p>Time profile → task type → transaction/program → statistical record.</p></div><label className="rca26Upload"><input type="file" multiple accept=".zip,.xlsx,.xls,.csv" onChange={e=>upload(e.target.files)}/>{busy?'Parsing…':'Upload ST03N Pack'}</label></header>
  <nav className="rca26Tabs compact"><a href="#st03n-time">Time Profile</a><a href="#st03n-workload">Workload</a><a href="#st03n-records">Top Records</a><a href="#st03n-evidence">Evidence</a></nav>
  <section className="rca26MetricStrip st03nStrip"><Metric label="Evidence coverage" value={`${ok}/${REQUIRED_ST03N.length}`} meta={`${a?.totalRows||0} normalized rows`} tone={ok===REQUIRED_ST03N.length?'good':'warn'}/><Metric label="Pack date" value={packDate} meta={files.length?`${files.length} files`:status}/><Metric label="Peak hour avg response" value={peak?`${n(peak.avgResponseMs,1)} ms`:'—'} meta={peak?.interval||'Time Profile'}/><Metric label="Top workload total response" value={tx?sh(tx.object,22):'—'} meta={tx?`${n(tx.totalResponseSec)} s · ${n(tx.steps)} steps`:'Transaction Standard'}/><Metric label="Top response record" value={resp?sh(resp.label,22):'—'} meta={resp?`${n(resp.responseMs)} ms · ${resp.timestamp}`:'Top Response'}/><Metric label="Source consistency" value={a?`${a.consistencyCheckCount||0} CHECK`:'—'} meta="Total response vs avg response × steps" tone={a?.consistencyCheckCount?'warn':'good'}/></section>
  <div className="rca26Grid st03nMain" id="st03n-time"><section className="rca26Panel"><div className="rca26PanelHead"><div><h2>Time Profile</h2><p>Average response, DB, CPU and wait by exported ST03N interval.</p></div><span className="rca26Tag">24h workload</span></div>{a?.timeProfile?.length?<div className="rca26Chart tall wideChart"><ResponsiveContainer width="100%" height="100%"><LineChart data={a.timeProfile} margin={{top:10,right:20,left:0,bottom:28}}><CartesianGrid strokeDasharray="3 6" vertical={false}/><XAxis dataKey="interval"/><YAxis/><Tooltip content={<Tip/>}/><Legend/><Line type="linear" dataKey="avgResponseMs" name="Avg Response" stroke="#4d8fff" strokeWidth={2.4} dot/><Line type="linear" dataKey="avgDbMs" name="Avg DB" stroke="#35d4cf" strokeWidth={2} dot/><Line type="linear" dataKey="avgCpuMs" name="Avg CPU" stroke="#f5a623" strokeWidth={2} dot/><Line type="linear" dataKey="avgWaitTotalMs" name="Wait + Roll" stroke="#9d79ff" strokeWidth={2} dot/><Brush dataKey="interval" height={20}/></LineChart></ResponsiveContainer></div>:<div className="rca26Empty">{status}</div>}</section><section className="rca26Panel compactPanel"><div className="rca26PanelHead"><div><h2>Task Type Overview</h2><p>Aggregate workload; not mixed with transaction/statistical records.</p></div></div><Table heads={['Task Type',numH('Steps'),numH('Avg Resp'),numH('DB'),numH('CPU'),numH('Wait+Roll')]} rows={(a?.taskTypes||[]).map(r=><tr key={r.taskType}><td>{r.taskType}</td><td className="num">{n(r.steps)}</td><td className="num">{n(r.avgResponseMs,1)} ms</td><td className="num">{n(r.avgDbMs,1)}</td><td className="num">{n(r.avgCpuMs,1)}</td><td className="num">{n(r.avgWaitTotalMs,1)}</td></tr>)}/></section></div>
  <section className="rca26Panel rca26Deferred" id="st03n-workload"><div className="rca26PanelHead"><div><h2>Average Response Decomposition — Top Workload</h2><p>Unattributed = response minus known DB/CPU/wait/load components; it is not a root-cause classification.</p></div></div>{dec.length?<div className="rca26Chart tall wideChart"><ResponsiveContainer width="100%" height="100%"><BarChart data={dec} margin={{top:8,right:18,left:0,bottom:72}}><CartesianGrid strokeDasharray="3 6" vertical={false}/><XAxis dataKey="name" angle={-28} textAnchor="end" interval={0} height={82} tickFormatter={v=>sh(v,20)}/><YAxis/><Tooltip formatter={v=>`${n(v,1)} ms`}/><Legend/><Bar stackId="a" dataKey="db" name="DB" fill="#35d4cf"/><Bar stackId="a" dataKey="cpu" name="CPU" fill="#4d8fff"/><Bar stackId="a" dataKey="wait" name="Wait" fill="#9d79ff"/><Bar stackId="a" dataKey="rollWait" name="Roll Wait" fill="#7550d8"/><Bar stackId="a" dataKey="load" name="Load" fill="#f5a623"/><Bar stackId="a" dataKey="unattributed" name="Unattributed" fill="#586a74"/></BarChart></ResponsiveContainer></div>:<div className="rca26Empty compact">No transaction data.</div>}</section>
  <div className="rca26Grid st03nWorkloadGrid rca26Deferred"><section className="rca26Panel"><div className="rca26PanelHead"><div><h2>Top Workload by Total Response</h2><p>Technical &lt;...&gt; objects remain in details but do not dominate this ranking.</p></div></div><div className="rca26Bars">{workload.slice(0,8).map(r=><div className="rca26BarRow workload" key={`${r.object}-${r.jobName}`}><label>{r.object}</label><div className="rca26BarTrack"><div className="rca26BarFill" style={{width:`${Math.max(2,Number(r.totalResponseSec||0)/max*100)}%`}}/></div><strong>{n(r.totalResponseSec)}s</strong></div>)}</div></section><section className="rca26Panel"><div className="rca26PanelHead"><div><h2>Transaction / Program Details</h2><p>Source values are preserved; consistency only flags mismatches and never rewrites the data.</p></div></div><Table className="jobs" heads={['Scope','Object','Background Job',numH('Steps'),numH('Total Resp'),numH('Avg Resp'),'Consistency',numH('Avg DB'),numH('Avg CPU'),numH('Avg Wait+Roll')]} rows={txRows.map((r,i)=><tr key={`${r.object}-${i}`}><td><span className={`rca26Scope ${r.technical?'technical':'workload'}`}>{r.technical?'TECH':'WORKLOAD'}</span></td><td>{r.object}</td><td>{r.jobName||'—'}</td><td className="num">{n(r.steps)}</td><td className="num">{n(r.totalResponseSec)} s</td><td className="num">{n(r.avgResponseMs,1)} ms</td><td><span className={`rca26Status ${r.responseConsistency==='CHECK'?'warn':'ok'}`}>{r.responseConsistency}{r.responseConsistency==='CHECK'?` ${n(r.responseConsistencyPct,1)}%`:''}</span></td><td className="num">{n(r.avgDbMs,1)}</td><td className="num">{n(r.avgCpuMs,1)}</td><td className="num">{n(r.avgWaitTotalMs,1)}</td></tr>)}/>{(a?.transactions||[]).length>15?<button className="rca26ShowMore" onClick={()=>setAllTx(v=>!v)}>{allTx?'Show top 15':`Show all ${a.transactions.length}`}</button>:null}</section></div>
  <div className="rca26Grid two rca26Deferred" id="st03n-records"><section className="rca26Panel"><div className="rca26PanelHead"><div><h2>Top Response Statistical Records</h2><p>Individual records; extreme source values are retained, not normalized away.</p></div></div><Table className="records" heads={['Timestamp','Program / Tx','Task','WP','User',numH('Response'),numH('DB'),numH('CPU'),numH('Wait'),numH('Roll Wait')]} rows={respRows.map((r,i)=><tr key={`${r.timestamp}-${i}`} data-extreme={r.extreme}><td>{r.timestamp}</td><td>{r.program||r.transaction||r.label}</td><td>{r.taskType}</td><td>{r.wp}</td><td>{r.user}</td><td className="num">{n(r.responseMs)} ms</td><td className="num">{n(r.dbMs)}</td><td className="num">{n(r.cpuMs)}</td><td className="num">{n(r.waitMs)}</td><td className="num">{n(r.rollWaitMs)}</td></tr>)}/>{(a?.responseRecords||[]).length>15?<button className="rca26ShowMore" onClick={()=>setAllResp(v=>!v)}>{allResp?'Show top 15':`Show all ${a.responseRecords.length}`}</button>:null}</section><section className="rca26Panel"><div className="rca26PanelHead"><div><h2>Top DB Access Records</h2><p>Sequential/direct/change access time and logical-call volume.</p></div></div><Table className="records" heads={['Timestamp','Program / Tx','Task','WP',numH('DB Access'),numH('Logical Calls'),numH('Seq Reads'),numH('Direct Reads')]} rows={dbRows.map((r,i)=><tr key={`${r.timestamp}-${i}`}><td>{r.timestamp}</td><td>{r.program||r.transaction||r.label}</td><td>{r.taskType}</td><td>{r.wp}</td><td className="num">{n(r.dbAccessMs)} ms</td><td className="num">{n(r.logicalCalls)}</td><td className="num">{n(r.sequentialReads)}</td><td className="num">{n(r.directReads)}</td></tr>)}/>{(a?.dbRecords||[]).length>15?<button className="rca26ShowMore" onClick={()=>setAllDb(v=>!v)}>{allDb?'Show top 15':`Show all ${a.dbRecords.length}`}</button>:null}</section></div>
  <section className="rca26Panel rca26Deferred" id="st03n-evidence"><div className="rca26PanelHead"><div><h2>Evidence Coverage</h2><p>Parser status for the five expected ST03N exports.</p></div></div><div className="rca26Coverage">{REQUIRED_ST03N.map(req=>{const x=(a?.coverage||[]).find(r=>r.kind===req.key);return <div key={req.key} data-ok={x?.ok}><span>{req.label}</span><b>{x?.ok?'Parsed':'Missing'}</b><small>{x?.fileName||'—'}{x?.ok?` · ${x.rows} rows`:''}</small></div>})}</div></section>
  <section className="rca26Case rca26Deferred"><div><span>Evidence</span><strong>{files.length} uploaded file(s)</strong><small>{status}</small></div><div className="rca26CaseActions"><a className="rca26Link" href="#/cases">History</a><button className="rca26Btn" onClick={()=>document.getElementById('st03n-case-v121')?.toggleAttribute('open')}>Case</button></div></section><details className="rca26Disclosure" id="st03n-case-v121"><summary>Case persistence</summary><div className="rca26DisclosureBody"><CaseLinkPanel title="ST03N case" description="Persist only after validating workload evidence." caseId={caseLink.caseId} caseTitle={caseLink.caseTitle} recentCases={caseLink.recentCases} savingCase={caseLink.savingCase} creatingCase={caseLink.creatingCase} saveStatus={caseLink.saveStatus} onCaseIdChange={caseLink.setCaseId} onCaseTitleChange={caseLink.setCaseTitle} onCreateCase={()=>caseLink.createLinkedCase(a)} onSaveCurrent={()=>caseLink.persistAnalysis(a,files)} hasAnalysis={Boolean(a)} saveLabel="Save ST03N analysis"/></div></details>
 </div></section>
}
